application: houkago-no
version: 3
runtime: python27
api_version: 1
threadsafe: yes
  
handlers:
- url: /css
  static_dir: htdocs/css
- url: /fonts
  static_dir: htdocs/fonts
- url: /js
  static_dir: htdocs/js
- url: /img
  static_dir: htdocs/img

- url: /.*
  script: main.django_app

libraries:
- name: django
  version: "1.4"
